# Generated by Django 5.2.8 on 2026-01-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={},
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid so far', max_digits=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining balance to be paid', max_digits=15),
        ),
        migrations.AlterModelTable(
            name='invoice',
            table=None,
        ),
    ]
