# Generated by Django 5.2.8 on 2026-01-08 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_alter_invoice_options_invoice_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='user',
            field=models.OneToOneField(blank=True, help_text='User account linked to this supplier', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
