# Generated by Django 5.2.8 on 2026-01-13 10:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0003_supplier_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('AMENDED', 'Amended'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_amended', models.BooleanField(default=False)),
                ('amendment_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_approved', to=settings.AUTH_USER_MODEL)),
                ('budget_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_plans', to='pms.budgetyear')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_plans', to='pms.department')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procurement_plans',
                'ordering': ['-created_at'],
                'unique_together': {('budget_year', 'department')},
            },
        ),
        migrations.CreateModel(
            name='ProcurementPlanItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('GOODS', 'Goods'), ('SERVICES', 'Services'), ('WORKS', 'Works')], max_length=20)),
                ('description', models.TextField()),
                ('specifications', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('procurement_method', models.CharField(choices=[('OPEN_TENDER', 'Open Tender'), ('RESTRICTED_TENDER', 'Restricted Tender'), ('RFQ', 'Request for Quotation'), ('DIRECT_PROCUREMENT', 'Direct Procurement'), ('FRAMEWORK', 'Framework Agreement')], max_length=30)),
                ('planned_quarter', models.CharField(choices=[('Q1', 'Quarter 1 (Jul-Sep)'), ('Q2', 'Quarter 2 (Oct-Dec)'), ('Q3', 'Quarter 3 (Jan-Mar)'), ('Q4', 'Quarter 4 (Apr-Jun)')], max_length=2)),
                ('source_of_funds', models.CharField(help_text='e.g., Government Budget, Donor Funds, IGR', max_length=100)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('CARRIED_FORWARD', 'Carried Forward')], default='PLANNED', max_length=20)),
                ('quantity_requisitioned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_committed', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sequence', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_items', to='pms.budget')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_items', to='pms.item')),
                ('procurement_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pms.procurementplan')),
            ],
            options={
                'db_table': 'procurement_plan_items',
                'ordering': ['procurement_plan', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementPlanAmendment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amendment_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('amendment_type', models.CharField(choices=[('ADD_ITEM', 'Add New Item'), ('REMOVE_ITEM', 'Remove Item'), ('MODIFY_ITEM', 'Modify Existing Item'), ('BUDGET_CHANGE', 'Budget Change'), ('QUARTER_CHANGE', 'Quarter Change'), ('METHOD_CHANGE', 'Procurement Method Change')], max_length=20)),
                ('justification', models.TextField(help_text='Detailed reason for amendment')),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='plan_amendments/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_amendments_approved', to=settings.AUTH_USER_MODEL)),
                ('procurement_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='pms.procurementplan')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_amendments_requested', to=settings.AUTH_USER_MODEL)),
                ('plan_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='pms.procurementplanitem')),
            ],
            options={
                'db_table': 'procurement_plan_amendments',
                'ordering': ['-requested_at'],
            },
        ),
    ]
