# Generated by Django 5.2.8 on 2026-01-13 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0004_procurementplan_procurementplanitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='emergency_type',
            field=models.CharField(blank=True, choices=[('BREAKDOWN', 'Equipment Breakdown'), ('SAFETY', 'Safety/Health Emergency'), ('REGULATORY', 'Regulatory/Compliance Requirement'), ('DONOR', 'New Donor Funding'), ('ACADEMIC', 'New Academic Requirement'), ('OTHER', 'Other Emergency')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='hod_emergency_approval',
            field=models.BooleanField(default=False, help_text='HOD confirmed this is genuine emergency'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='is_planned',
            field=models.BooleanField(default=True, help_text='Whether this requisition is from procurement plan'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='plan_amendment',
            field=models.ForeignKey(blank=True, help_text='Link to plan amendment if required', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='pms.procurementplanamendment'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='plan_deviation_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='plan_deviation_approved_by',
            field=models.ForeignKey(blank=True, help_text='Senior officer who approved deviation from plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_deviations_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requisition',
            name='procurement_plan_item',
            field=models.ForeignKey(blank=True, help_text='Link to approved procurement plan item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='pms.procurementplanitem'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='requires_plan_amendment',
            field=models.BooleanField(default=False, help_text='Whether plan needs to be amended for this requisition'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='emergency_justification',
            field=models.TextField(blank=True, help_text='Detailed justification for unplanned/emergency procurement'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='is_emergency',
            field=models.BooleanField(default=False, help_text='Emergency procurement flag'),
        ),
    ]
