# Generated by Django 5.2.8 on 2026-01-15 11:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0005_requisition_emergency_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCommittee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('committee_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('committee_type', models.CharField(choices=[('TECHNICAL', 'Technical Evaluation'), ('FINANCIAL', 'Financial Evaluation'), ('COMBINED', 'Combined Evaluation')], max_length=20)),
                ('name', models.CharField(max_length=300)),
                ('appointment_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('terms_of_reference', models.TextField()),
                ('evaluation_guidelines', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chairperson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committees_chaired', to=settings.AUTH_USER_MODEL)),
                ('secretary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committees_secretaried', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_committees', to='pms.tender')),
            ],
            options={
                'db_table': 'evaluation_committees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CombinedEvaluationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('average_technical_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('technical_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_technically_qualified', models.BooleanField(default=False)),
                ('technical_pass_mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('average_financial_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('financial_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('combined_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_rank', models.IntegerField(blank=True, null=True)),
                ('is_recommended', models.BooleanField(default=False)),
                ('recommendation_notes', models.TextField(blank=True)),
                ('is_disqualified', models.BooleanField(default=False)),
                ('disqualification_reason', models.TextField(blank=True)),
                ('evaluation_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='combined_evaluation', to='pms.bid')),
                ('evaluated_by_committee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_results', to='pms.evaluationcommittee')),
            ],
            options={
                'db_table': 'combined_evaluation_results',
                'ordering': ['bid__tender', '-combined_score'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('report_type', models.CharField(choices=[('PRELIMINARY', 'Preliminary Evaluation'), ('TECHNICAL', 'Technical Evaluation'), ('FINANCIAL', 'Financial Evaluation'), ('COMBINED', 'Combined Evaluation'), ('FINAL', 'Final Recommendation')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('executive_summary', models.TextField()),
                ('methodology', models.TextField()),
                ('findings', models.TextField()),
                ('recommendations', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('report_document', models.FileField(blank=True, null=True, upload_to='evaluation_reports/')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_reports_approved', to=settings.AUTH_USER_MODEL)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='pms.evaluationcommittee')),
                ('recommended_bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_in_reports', to='pms.bid')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_reports_submitted', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_reports', to='pms.tender')),
            ],
            options={
                'db_table': 'evaluation_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialEvaluationCriteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evaluation_method', models.CharField(choices=[('LOWEST_PRICE', 'Lowest Evaluated Price'), ('FIXED_BUDGET', 'Fixed Budget'), ('QUALITY_COST', 'Quality and Cost Based')], max_length=20)),
                ('technical_weight', models.DecimalField(decimal_places=2, default=70, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('financial_weight', models.DecimalField(decimal_places=2, default=30, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('uses_formula', models.BooleanField(default=True)),
                ('formula_description', models.TextField(blank=True, help_text='e.g., Score = (Lowest Price / Bid Price) × 100')),
                ('check_price_reasonability', models.BooleanField(default=True)),
                ('acceptable_variance_percentage', models.DecimalField(decimal_places=2, default=15, help_text="Acceptable variance from engineer's estimate", max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_criteria', to='pms.tender')),
            ],
            options={
                'db_table': 'financial_evaluation_criteria',
            },
        ),
        migrations.CreateModel(
            name='TechnicalEvaluationCriteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criterion_name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('minimum_specification', models.TextField()),
                ('response_type', models.CharField(choices=[('YES_NO', 'Yes/No'), ('DOCUMENT', 'Document Upload'), ('NUMERIC', 'Numeric Value'), ('TEXT', 'Text Description')], max_length=20)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('is_pass_fail', models.BooleanField(default=False, help_text='If true, failing this criterion disqualifies the bid')),
                ('max_score', models.DecimalField(decimal_places=2, help_text='Maximum points for this criterion', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight_percentage', models.DecimalField(decimal_places=2, help_text='Weight in overall technical score', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('scoring_guidelines', models.TextField(blank=True, help_text='How to score this criterion')),
                ('sequence', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_criteria', to='pms.tender')),
            ],
            options={
                'db_table': 'technical_evaluation_criteria',
                'ordering': ['tender', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('CHAIRPERSON', 'Chairperson'), ('SECRETARY', 'Secretary'), ('MEMBER', 'Member'), ('OBSERVER', 'Observer')], max_length=20)),
                ('expertise_area', models.CharField(blank=True, max_length=200)),
                ('has_conflict', models.BooleanField(default=False)),
                ('conflict_details', models.TextField(blank=True)),
                ('appointed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_members', to='pms.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to=settings.AUTH_USER_MODEL)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='pms.evaluationcommittee')),
            ],
            options={
                'db_table': 'committee_members',
                'ordering': ['committee', 'role'],
                'unique_together': {('committee', 'user')},
            },
        ),
        migrations.CreateModel(
            name='FinancialEvaluationScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quoted_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_arithmetic_correct', models.BooleanField(default=True)),
                ('arithmetic_notes', models.TextField(blank=True)),
                ('is_within_budget', models.BooleanField(default=True)),
                ('is_price_reasonable', models.BooleanField(default=True)),
                ('variance_from_estimate', models.DecimalField(decimal_places=2, help_text='Percentage variance', max_digits=5)),
                ('financial_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weighted_financial_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('comments', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_scores', to='pms.bid')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_scores_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'financial_evaluation_scores',
                'ordering': ['bid', 'financial_score'],
                'unique_together': {('bid', 'evaluator')},
            },
        ),
        migrations.CreateModel(
            name='BidTechnicalResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_text', models.TextField(blank=True)),
                ('response_value', models.CharField(blank=True, max_length=200)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='bid_technical_documents/')),
                ('supplier_remarks', models.TextField(blank=True)),
                ('compliance_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('COMPLIANT', 'Compliant'), ('NON_COMPLIANT', 'Non-Compliant'), ('PARTIALLY_COMPLIANT', 'Partially Compliant')], default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_responses', to='pms.bid')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_responses', to='pms.technicalevaluationcriteria')),
            ],
            options={
                'db_table': 'bid_technical_responses',
                'ordering': ['bid', 'criterion__sequence'],
                'unique_together': {('bid', 'criterion')},
            },
        ),
        migrations.CreateModel(
            name='TechnicalEvaluationScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('weighted_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_compliant', models.BooleanField(default=True)),
                ('comments', models.TextField(blank=True)),
                ('justification', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_scores', to='pms.bid')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='pms.technicalevaluationcriteria')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_scores_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'technical_evaluation_scores',
                'ordering': ['bid', 'criterion__sequence'],
                'unique_together': {('bid', 'criterion', 'evaluator')},
            },
        ),
    ]
