# Generated by Django 5.2.8 on 2026-01-15 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0006_evaluationcommittee_combinedevaluationresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='award_approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='award_recommendation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='evaluation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='evaluation_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='financial_evaluation_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tender',
            name='preliminary_evaluation_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tender',
            name='requires_technical_evaluation',
            field=models.BooleanField(default=True, help_text='Whether technical evaluation is required'),
        ),
        migrations.AddField(
            model_name='tender',
            name='technical_evaluation_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tender',
            name='technical_pass_mark',
            field=models.DecimalField(decimal_places=2, default=70, help_text='Minimum technical score to qualify', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
