# Generated by Django 6.0.1 on 2026-02-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0008_bid_financial_evaluation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
